myapp2/config/routes.rb
Rails.application.routes.draw do
  get'/',to:'schedules#index'
  get'new',to:'schedules#new'
  post'new',to:'schedules#create'
  post'update',to:'schedules#update'
  
   resources:schedules
end

myapp2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

myapp2/app/models/plan.rb
class Plan < ApplicationRecord
   validates :title, presence: true
      validates :startTime, presence: true 
      validates :endTime, presence: true
     

    
end

myapp2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

myapp2/app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  
  def index
   @plan=Plan.all#planテーブルのデータ取得
   
  end
  
  def new
     @plan = Plan.new
    
  end
  
    def create
      @plan = Plan.new(plan_params)
      @plan.save
      
       if @plan.save
         flash[:notice] = "ユーザーを新規登録しました"
         redirect_to "/"
       else
           render "new"
       end
        
    end
    
    def plan_params
        params.permit(:title, :startTime, :endTime,:dayAll,:memo)
        #params.require(:plan)はplan.newで定義しているので不要
        #（もともとplanテーブルに保存されるものとして送信されているので
        #params.require(:plan)と書くとだぶる？）
    end
    
    def show
      @plan = Plan.find(params[:id])
    end
    
    def edit
         @plan = Plan.find(params[:id])
    end 
    
     def update
      @plan = Plan.find(params[:id])
      if @plan.update(params.require(:plan).permit(:title, :startTime,:dayAll, :endTime, :memo))
        flash[:notice] = "「#{@plan.id}番の#{@plan.title}」の情報を更新しました"
        redirect_to "/"
      else
        render "edit"
      end
     end   
    
    def destroy
         @plan = Plan.find(params[:id])
      @plan.destroy
      flash[:notice] = "ユーザーを削除しました"
      redirect_to "/"
    end
    protect_from_forgery
    
end

myapp2/app/helpers/application_helper.rb
module ApplicationHelper
end

myapp2/app/helpers/schedules_helper.rb
module SchedulesHelper
end

myapp2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <h1>Ruby on Rails スケジュール管理アプリ</h1>
   </header>
  
   <%= yield %>
   
   <footer>
     
   <h1>現在の日時：<%=Time.zone.now.to_s(:datetime_jp)%> スケジュール合計:<%=Plan.count %></h1>
    
    
   </footer>
   
  </body>
</html>

myapp2/app/views/schedules/edit.html.erb
<h3>編集</h3>
   <%= form_with url: schedule_path,model: @plan,local: true do |f| %>
   <!--editアクションの@planを取得するために-->
   <!--urlを書いた後にモデル名@planを書いた-->
   
      <table>
        <tr>
          <th><%= f.label :title ,"タイトル" %></th>
          <td><%= f.text_field :title ,size:"50"%></td>
        </tr>
 
        <tr>
          <th><%= f.label :startTime ,"開始日" %></th>
          <td><%= f.date_field :startTime,size:"50"%></td>
        </tr>
 
        <tr>
          <th><%= f.label :endTime ,"終了日" %></th>
          <td><%= f.date_field :endTime,size:"50"%></td>
        </tr>
        
       <tr>
        <th><%= f.label :dayAll ,"終日" %></th>
       <td><%= f.check_box :dayAll%><p>終日の場合はチェックをします</p></td>
       </tr> 
       
        <tr>
          <th><%= f.label :memo ,"スケジュールメモ" %></th>
          <td><%= f.text_area :memo,size:"50x10"%></td>
        </tr>
      </table>
        <ul>
          <li><%= f.submit "編集を完了する" %></li>
          <li><%= link_to "一覧に戻る", "/" %></li>
        </ul>
 <%end%>

myapp2/app/views/schedules/index.html.erb
    <h1>投稿一覧ページ</h1>
      
      <table>
      <thead>
        <tr>
          <th>ID</th>
          <th>タイトル</th>
          <th>開始日</th>
          <th>終了日</th>
          <th>終日</th>
          <th>スケジュール更新日時</th>
          <th>確認</th>
          <th>編集</th>
          <th>削除</th>
        </tr>
      </thead>
      
      <tbody>
        <% @plan.each do |plan| %>
          <tr>
            <td><%= plan.id %></td>
            <td><%= plan.title %></td>
            <td><%= plan.startTime.to_s(:datetime_jp) %></td>
            <td><%= plan.endTime.to_s(:datetime_jp)%></td>
            <td><% if plan.dayAll == 1 %>
                <p>○</p>
                <% end %>
            </td>
            <td><%= plan.updated_at.strftime("%Y年%m月%d日%-H時%M分")%></td>
           <td><%= link_to "確認",schedule_path(plan)%></td>
           <!--(plan.id)の部分でidの値を渡している-->
           <td><%= link_to "編集",edit_schedule_path(plan) %></td>
      <td><%= link_to "削除", schedule_path(plan), method: :delete, data: { confirm: "本当に削除しますか？" } %></td>
        <% end %>
        </tr>
      <% if flash.notice %>
      <p class="notice"><%= flash.notice %></p>
      <% end %>

      </tbody>
       </table>
       <%= link_to "スケジュール新規登録","new"%>
       

myapp2/app/views/schedules/new.html.erb
<h1>新規スケジュール作成ページ</h1>
<h2>スケジュール新規作成</h2>
   <%= render "shared/error", obj: @plan %>
 <%= form_with url: '',local: true ,method: @plan do |f| %>　　<!--form_forだとうまく送れなかった{form_for '@plan' do |f|}-->
      <table class = "new">
        <tr>
          <th><%= f.label :title ,"タイトル" %></th>
          <td><%= f.text_field :title ,size:"50"%></td>
        </tr>
        <tr>
          <th><%= f.label :startTime ,"開始日" %></th>
          <td><%= f.date_field :startTime,size:"100"%></td>
        </tr>
 
        <tr>
          <th><%= f.label :endTime ,"終了日" %></th>
          <td><%= f.date_field :endTime,size:"100"%></td>
        </tr>
        <tr>
        <th><%= f.label :dayAll ,"終日" %></th>
       <td><%= f.check_box :dayAll%><p>終日の場合はチェックをします</p></td>
       </tr>
        <tr>
          <th><%= f.label :memo ,"スケジュールメモ" %></th>
          <td><%= f.text_area :memo,size:"50x10"%></td>
        </tr>
      </table>
    <ul>
      <li><%= f.submit "登録完了する"%></li>
      <li><%= link_to "スケジュール一覧に戻る","/"%></li>
    </ul>
 <%end%>
 

myapp2/app/views/schedules/show.html.erb
<h3>スケジュール確認</h3>
 
    <table>
      <tr>
        <th>タイトル</th>
        <td><%= @plan.title %></td>
      </tr>
      <tr>
        <th>開始日</th>
        <td><%= @plan.startTime %></td>
      </tr>
       <tr>
        <th>終了日</th>
        <td><%= @plan.endTime %></td>
      </tr>
      <tr>
        <th>更新日時</th>
        <td><%= @plan.updated_at .to_s(:datetime_jp) %></td>
      </tr>
      <tr>
        <th>終日</th>
       <td><% if @plan.dayAll%>
                <p>○</p>
                <% end %></td>
       </tr>
      <tr>
        <th>スケジュールメモ</th>
        <td><%= @plan.memo %></td>
      </tr>
    </table>
 
    <div>
      
      <ul>
        <li><%= link_to "ユーザー情報一覧に戻る","/" %></li>
        <li><%= link_to "スケジュールを編集する",edit_schedule_path(@plan) %></li>
        <li><%= link_to "削除", schedule_path(@plan), method: :delete, data: { confirm: "本当に削除しますか？" } %></li>
      </ul>
      
    </div>

myapp2/app/views/shared/_error.html.erb
<% if obj.errors.any? %>
<p><%=obj.errors.count%>個のエラーがあります</p>
      <% obj.errors.full_messages.each do |message| %>
        <ul>
          <li><%= message %></p>
        </ul>
      <% end %>
    <% end %>
    